### ISSUE TITLE
Hash is always the same

### ISSUE THREAD

**Issue by sigmaticsMUC** [drriguz/encryptions#1]
Uint8List password = utf8.encode('password');
    Uint8List salt = utf8.encode("ustamm");

    Argon2 argon2 = Argon2(iterations: 16, hashLength: 32, memory: 256, parallelism: 2);
    Uint8List hash = await argon2.argon2i(password, salt);
    print('THIS IS HASH: ' + hash.toString());
    

Result is always:

THIS IS HASH: Argon2 params:16/2/256/32 

Am I doing something wrong? Seems like the hashing does not return the salted & hashed password?!

**Comment by drriguz** [comment]
yeah, this is incorrect, have you ever tried to run the example app? can you get the expected result like ![this](https://raw.githubusercontent.com/soleverlee/encryptions/master/report-ios.png) ?

**Comment by drriguz** [comment]
@sigmaticsMUC  I got the reason: salt must be at least 8 characters long, according to the [wiki](https://en.wikipedia.org/wiki/Argon2):

salt (S):           Bytes (8..232-1)    Salt (16 bytes recommended for password hashing)

Otherwise you will get like this:
```
THIS IS HASH: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```
