### ISSUE TITLE
No implementation found for method aesDecrypt on channel encryptions

### ISSUE THREAD

**Issue by mrtnetwork** [drriguz/encryptions#11]
plugin work under profile or debug mode but after build project with realease mode encryption, decryption not working, i tracking encryption, decryt log in realease mode with flutter logs and i get No implementation found for method aesDecrypt on channel encryptions exption when call ```decrypt``` method

my code 
```
Uint8List _data = Uint8List.fromList(base64Decode(data));
final Uint8List iv = Uint8List.fromList(utf8.encode(aesIV));
final Uint8List key256 = Uint8List.fromList(utf8.encode(aesKey));
 AES aes = AES.ofCBC(key256, iv, PaddingScheme.PKCS5Padding);
_data = await aes.decrypt(_data);// i got exception here just after build release mode
```

**Comment by mrtnetwork** [comment]
add this line to progurd config fix issue, 
Is there a plan in your program to add a RSA ? I use Rsa to encrypt aes IV and I have to use another plugin
```
-keep class com.riguz.** { *; }
```

**Comment by drriguz** [comment]
Thanks for feedback, unfortunately I'm currently focusing on other stuff thus not available for manitaining this repository.
Since implement RSA does not require c++ integration, it shoule be easy to add it to the plugin!
