### ISSUE TITLE
Unable to call properly after packaging APK

### ISSUE THREAD

**Issue by 7-bit11** [drriguz/encryptions#13]
Hello, I encountered a serious problem when using this plug-in. Calling the plug-in after packaging the program will prompt the exception Unhandled Exception: MissingPluginException (No implementation found for method aesEncrypt on channel encryption package: fluent/src/services/platform_channel. dart: 332

**Comment by drriguz** [comment]
Hi，this plugin is no longer maintained. It's recommended to use other packages instead, eg. https://pub.dev/packages/pointycastle
