### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by aaronlinsky** [drriguz/encryptions#2]
I'm unable to get this package to work. I receive the following error when I attempt to call `argon2i`.
```
MissingPluginException (MissingPluginException(No implementation found for method argon2i on channel encryptions))
```
this is my call:
```
 Argon2 argon2 = Argon2(iterations: 16, hashLength: 64, memory: 256, parallelism: 2);
 var hash = await argon2.argon2i(bytes, salt);
```

**Comment by aaronlinsky** [comment]
@soleverlee - Is there any chance you could look into this issue?

**Comment by drriguz** [comment]
I'm sorry but this project is not under maintenance temporarily due to that recently I switch to a MBP 2019 which does not have USB port. 

But I'll suggest having a look at my other project [Ben App](https://github.com/soleverlee/ben/) which uses this plugin and it has been built successfully both in the Android and IOS platforms.

**Comment by JAICHANGPARK** [comment]
Hi all 

I had simillar issue about this when I installed release apk file 

>Unhandled Exception: MissingPluginException(No implementation found for method aesEncrypt on channel encryptions)

```
 AES aes = AES.ofECB(key128, PaddingScheme.NoPadding);
 Uint8List encrypted = await aes.encrypt(plain);
 Uint8List decrypted = await aes.decrypt(encrypted);
```

**Comment by drriguz** [comment]
Hi, 
@JAICHANGPARK @aaronlinsky could you check whether you got the same issue as [MissingPluginException on Android after flutter build, but it works fine on flutter run --release](https://github.com/flutter/flutter/issues/50338)

**Comment by drriguz** [comment]
Since no more details are provided I'll close this issue, feel free to re-open it if it's still not resolved.
