### ISSUE TITLE
java.lang.NullPointerException: println needs a message

### ISSUE THREAD

**Issue by JAICHANGPARK** [drriguz/encryptions#3]
I had some problem about AES.ofECB Mode (AES-128)
Should plain be 16 bytes?

If the length is 16 bytes, there is no problem in use.

```  
Uint8List key128 = hex.decode("323232323323232323232323232323232");
Uint8List plain = Uint8List.fromList("3232323232");
AES aes = AES.ofECB(key128, PaddingScheme.NoPadding);
Uint8List encrypted = await aes.encrypt(plain);
```

>E/AndroidRuntime(24555): java.lang.NullPointerException: println needs a message
E/AndroidRuntime(24555): 	at android.util.Log.println_native(Native Method)
E/AndroidRuntime(24555): 	at android.util.Log.e(Log.java:240)
E/AndroidRuntime(24555): 	at com.riguz.encryptions.FlutterCallExecutor.execute(FlutterCallExecutor.java:82)
E/AndroidRuntime(24555): 	at com.riguz.encryptions.FlutterCallExecutor.access$000(FlutterCallExecutor.java:20)
E/AndroidRuntime(24555): 	at com.riguz.encryptions.FlutterCallExecutor$1.run(FlutterCallExecutor.java:53)
E/AndroidRuntime(24555): 	at java.lang.Thread.run(Thread.java:764)

**Comment by drriguz** [comment]
yes, if you choose `NoPadding` then you need to make sure that the data length is N*(block size) (N∈(1, 2,...n) 
read more about the block size and padding here: [Block Size and Padding](https://tools.ietf.org/html/rfc3602#section-2.4)
