### ISSUE TITLE
blake2.h:21:10: error: 'argon2.h' file not found with <angled> include; use "quotes" instead

### ISSUE THREAD

**Issue by RitaLing** [drriguz/encryptions#4]
Running Xcode build...                                                  
                                                   
Xcode build done.                                            8.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    While building module 'encryptions' imported from /Users/allen/huami/flutter/debugger/module/debugger_module/.ios/Flutter/FlutterPluginRegistrant/Classes/GeneratedPluginRegistrant.m:26:
    In file included from <module-includes>:1:
    In file included from /Users/allen/huami/flutter/debugger/module/debugger_module/.ios/Pods/Target Support Files/encryptions/encryptions-umbrella.h:15:
    /Users/allen/up up/flutter_sdk/flutter/.pub-cache/hosted/pub.dartlang.org/encryptions-0.0.6/ios/Classes/argon2/blake2.h:21:10: error: 'argon2.h' file not found with <angled> include; use "quotes" instead
    #include <argon2.h>
             ^~~~~~~~~~
             "argon2.h"
    1 error generated.
    /Users/allen/huami/flutter/debugger/module/debugger_module/.ios/Flutter/FlutterPluginRegistrant/Classes/GeneratedPluginRegistrant.m:26:9: fatal error: could not build module 'encryptions'
    #import <encryptions/EncryptionsPlugin.h>
     ~~~~~~~^
    2 errors generated.
    error: the following command failed with exit code 1 but produced no further output
    CompileC /Users/allen/Library/Developer/Xcode/DerivedData/Runner-cfbuvmlqqrfslnaeiullzkfptahb/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FlutterPluginRegistrant.build/Objects-normal/arm64/GeneratedPluginRegistrant.o
    /Users/allen/huami/flutter/debugger/module/debugger_module/.ios/Flutter/FlutterPluginRegistrant/Classes/GeneratedPluginRegistrant.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

**Comment by drriguz** [comment]
do you still have this issue? please re-open this issue if you need any help.
