### ISSUE TITLE
uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by peekpt** [drriguz/encryptions#6]
The plugin `encryptions` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
---
Hi, I working on a project using your plugin, it's great because it accepts Uint8List directly but I got this warning running on Android 11 phone. It's important to me to know if you are going to upgrade it in a future to use the new v2 Android embedding. Thanks!

**Comment by drriguz** [comment]
Thanks for your feedback, I'll take a look at this.

**Comment by peekpt** [comment]
Any update? I needed to add 
`-keep class com.riguz.encryptions.** { *; }` to android/app/proguard-rules.pro to get it working with release

**Comment by drriguz** [comment]
A fixed version(1.1.0) has been uploaded in pub.dev, please try it.  I'll close the issue, feel free to re-open it if you find any issue!

I also noticed the issue you mentioned above, which is also described in https://github.com/drriguz/encryptions/issues/7.

However I did not found any official recommendation to fix this, so I disabled `shrink` in build configuration. Let me know if this works for you!
