### ISSUE TITLE
The plugin `encryptions` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by ghost** [drriguz/encryptions#7]
The plugin does not work anymore with Flutter 2.5 or greater (in release mode). Need android embedding 2.0. 
![image](https://user-images.githubusercontent.com/85259282/137397932-fe6deda3-73db-4ac5-b362-4fae4d165c7c.png)
![image](https://user-images.githubusercontent.com/85259282/137398003-8adb767a-1e22-45fe-965a-0db7a069c9c8.png)

**Comment by drriguz** [comment]
A fixed version(1.1.0) has been uploaded in pub.dev, please try it.  I'll close the issue, feel free to re-open it if you find any issue!

**Comment by peekpt** [comment]
@drriguz 
It seems to be working but IMO it's better add to documentation to add `-keep class com.riguz.encryptions.** { *; }` to the `proguard-rules.pro` file in `android/app/` to work in  release mode.
